const USER_SIDE_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const CONFLICT_ERROR = 409;

const SERVER_SIDE_ERROR = 500;

const OK = 200;
const CREATED = 201;

module.exports = {
  USER_SIDE_ERROR,
  NOT_FOUND_ERROR,
  SERVER_SIDE_ERROR,
  OK,
  CREATED,
  UNAUTHORIZED_ERROR,
  FORBIDDEN_ERROR,
  CONFLICT_ERROR,
};
